language: rust
rust:
  - stable
cache: cargo

before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - which rustfmt || cargo install rustfmt

script:
  - ./scripts/install-deps.sh
  - cargo fmt -- --write-mode=diff
  - cargo build
  - cargo build --release
  - cargo test
  - cargo test --release
  - cd test-files && cargo run --release -- build && cd -
  - cd test-files && cargo run -- build && cd -
