[package]
name = "md-pdf"
version = "0.1.0"
authors = ["Jake Howard <git@theorangeone.net>"]

[dependencies]
clap = "2.25.0"
pandoc = "0.6.2"
serde = "1.0.10"
serde_derive = "1.0.10"
serde_yaml = "0.7.1"
