version: 2.0

jobs:
    build:
        docker:
            - image: jimmycuadra/rust
        working_directory: ~/md-pdf
        steps:
            - checkout
            - restore_cache:
                keys:
                    - cargo-{{ checksum "Cargo.lock" }}
            - run: which rustfmt || cargo install rustfmt
            - run: apt update && apt install -y wget
            - run: make lib
            - run: ./.circleci/wkhtmltopdf.sh
            - run: cargo fmt -- --write-mode=diff
            - run: make build
            - run: make release
            - save_cache:
                key: cargo-{{ checksum "Cargo.lock" }}
                paths:
                    - ~/.cargo
                    - target/
            - run: make test
            - run:
                command: cargo run -- build
                working_directory: ~/md-pdf/test-files
            - run:
                command: cargo run --release -- build
                working_directory: ~/md-pdf/test-files
